export type {
	ApiMethods,
	InputMedia,
	InputMediaAnimation,
	InputMediaAudio,
	InputMediaDocument,
	InputMediaLink,
	InputMediaLivePhoto,
	InputMediaLocation,
	InputMediaPhoto,
	InputMediaSticker,
	InputMediaVenue,
	InputMediaVideo,
	InputMediaVoiceNote,
	InputPaidMedia,
	InputPaidMediaLivePhoto,
	InputPaidMediaPhoto,
	InputPaidMediaVideo,
	InputProfilePhoto,
	InputProfilePhotoAnimated,
	InputProfilePhotoStatic,
	InputSticker,
	InputStoryContent,
	InputStoryContentPhoto,
	InputStoryContentVideo,
	Opts,
	Ret,
} from "./bot-api.js";
