export type {
	ApiMethods,
	InputMedia,
	InputMediaAnimation,
	InputMediaAudio,
	InputMediaDocument,
	InputMediaPhoto,
	InputMediaVideo,
	InputPaidMedia,
	InputPaidMediaPhoto,
	InputPaidMediaVideo,
	InputProfilePhoto,
	InputProfilePhotoAnimated,
	InputProfilePhotoStatic,
	InputSticker,
	InputStoryContent,
	InputStoryContentPhoto,
	InputStoryContentVideo,
	Opts,
	Ret,
} from "./bot-api.js";
