export type {
	EncryptedCredentials,
	EncryptedPassportElement,
	PassportData,
	PassportElementError,
	PassportElementErrorDataField,
	PassportElementErrorFile,
	PassportElementErrorFiles,
	PassportElementErrorFrontSide,
	PassportElementErrorReverseSide,
	PassportElementErrorSelfie,
	PassportElementErrorTranslationFile,
	PassportElementErrorTranslationFiles,
	PassportElementErrorUnspecified,
	PassportFile,
} from "./bot-api.js";
