export type {
  AffiliateInfo,
  Invoice,
  LabeledPrice,
  OrderInfo,
  PaidMediaPurchased,
  PreCheckoutQuery,
  RefundedPayment,
  RevenueWithdrawalState,
  RevenueWithdrawalStateFailed,
  RevenueWithdrawalStatePending,
  RevenueWithdrawalStateSucceeded,
  ShippingAddress,
  ShippingOption,
  ShippingQuery,
  StarTransaction,
  StarTransactions,
  SuccessfulPayment,
  TransactionPartner,
  TransactionPartnerAffiliateProgram,
  TransactionPartnerChat,
  TransactionPartnerFragment,
  TransactionPartnerOther,
  TransactionPartnerTelegramAds,
  TransactionPartnerTelegramApi,
  TransactionPartnerUser,
} from "./bot-api.ts";
