export type {
	BotCommandScope,
	BotCommandScopeAllChatAdministrators,
	BotCommandScopeAllGroupChats,
	BotCommandScopeAllPrivateChats,
	BotCommandScopeChat,
	BotCommandScopeChatAdministrators,
	BotCommandScopeChatMember,
	BotCommandScopeDefault,
	BotDescription,
	BotName,
	BotShortDescription,
	MenuButton,
	MenuButtonCommands,
	MenuButtonDefault,
	MenuButtonWebApp,
} from "./bot-api.js";
